SCENARIO_PRESETS = {
    "Custom": {
        "description": "Manual controls. Use this when exploring your own deployment assumptions.",
        "monthly_requests": 5_000_000,
        "max_latency_ms": 75,
        "min_accuracy": 0.70,
        "max_cost": 200,
        "traffic_pattern": "Burst",
        "serving_type": "Real-time",
        "deployment_type": "Hybrid",
        "latency_slo_ms": 100,
        "batch_size": 1,
        "autoscaling_enabled": True,
        "max_instance_utilization": 0.70,
        "optimize_for": "Balanced",
    },
    "Edge deployment": {
        "description": "Low-latency edge inference with constrained hardware and lower operating cost.",
        "monthly_requests": 1_000_000,
        "max_latency_ms": 50,
        "min_accuracy": 0.70,
        "max_cost": 100,
        "traffic_pattern": "Steady",
        "serving_type": "Real-time",
        "deployment_type": "Edge",
        "latency_slo_ms": 60,
        "batch_size": 1,
        "autoscaling_enabled": False,
        "max_instance_utilization": 0.70,
        "optimize_for": "Latency",
    },
    "Cloud inference": {
        "description": "Cloud-hosted inference with moderate traffic and balanced latency/cost goals.",
        "monthly_requests": 10_000_000,
        "max_latency_ms": 100,
        "min_accuracy": 0.72,
        "max_cost": 500,
        "traffic_pattern": "Burst",
        "serving_type": "Real-time",
        "deployment_type": "Cloud",
        "latency_slo_ms": 120,
        "batch_size": 1,
        "autoscaling_enabled": True,
        "max_instance_utilization": 0.65,
        "optimize_for": "Balanced",
    },
    "Cost optimized": {
        "description": "Minimizes monthly operating cost while respecting basic latency and accuracy constraints.",
        "monthly_requests": 5_000_000,
        "max_latency_ms": 150,
        "min_accuracy": 0.65,
        "max_cost": 80,
        "traffic_pattern": "Steady",
        "serving_type": "Batch",
        "deployment_type": "Hybrid",
        "latency_slo_ms": 180,
        "batch_size": 8,
        "autoscaling_enabled": True,
        "max_instance_utilization": 0.80,
        "optimize_for": "Cost",
    },
    "Low-carbon mode": {
        "description": "Prioritizes carbon and energy efficiency for sustainable AI deployment planning.",
        "monthly_requests": 5_000_000,
        "max_latency_ms": 120,
        "min_accuracy": 0.68,
        "max_cost": 300,
        "traffic_pattern": "Burst",
        "serving_type": "Batch",
        "deployment_type": "Hybrid",
        "latency_slo_ms": 150,
        "batch_size": 8,
        "autoscaling_enabled": True,
        "max_instance_utilization": 0.70,
        "optimize_for": "Carbon",
    },
    "High-throughput batch serving": {
        "description": "Large request volume where throughput and energy efficiency matter more than strict latency.",
        "monthly_requests": 30_000_000,
        "max_latency_ms": 300,
        "min_accuracy": 0.70,
        "max_cost": 1500,
        "traffic_pattern": "Spiky",
        "serving_type": "Batch",
        "deployment_type": "Cloud",
        "latency_slo_ms": 350,
        "batch_size": 32,
        "autoscaling_enabled": True,
        "max_instance_utilization": 0.75,
        "optimize_for": "Energy",
    },
}


def get_preset(name: str) -> dict:
    return SCENARIO_PRESETS.get(name, SCENARIO_PRESETS["Custom"])
